import React, {useEffect, useMemo, useState} from 'react';
import {Platform, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {NativeStackScreenProps} from '@react-navigation/native-stack';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import AnimatedGradientBackground from '../components/AnimatedGradientBackground';
import GlassCard from '../components/GlassCard';
import HamburgerButton from '../components/HamburgerButton';
import SideDrawerMenu from '../components/SideDrawerMenu';
import {useSubjects} from '../context/SubjectsContext';
import {RootStackParamList} from '../navigation/types';
import {loadAiPlanSnapshot, loadAiTasks, loadAiTimetable} from '../storage/aiStorage';
import {darkPalette, lightPalette, typography} from '../theme';
import {AITask, CoachTimeBlock} from '../types';
import {extractPlanTasksFromText} from '../utils/gemini';

type Props = NativeStackScreenProps<RootStackParamList, 'MyTasks'>;

const MyTasksScreen = ({navigation}: Props) => {
  const insets = useSafeAreaInsets();
  const {isDarkMode} = useSubjects();
  const palette = isDarkMode ? darkPalette : lightPalette;
  const [menuVisible, setMenuVisible] = useState(false);
  const [tasks, setTasks] = useState<AITask[]>([]);
  const [planSnapshot, setPlanSnapshot] = useState('');
  const [timetable, setTimetable] = useState<CoachTimeBlock[]>([]);

  useEffect(() => {
    const hydrate = async () => {
      const [loadedTasks, loadedPlan, loadedTimetable] = await Promise.all([
        loadAiTasks(),
        loadAiPlanSnapshot(),
        loadAiTimetable(),
      ]);
      setTasks(loadedTasks);
      setPlanSnapshot(loadedPlan);
      setTimetable(loadedTimetable);
    };

    hydrate();
  }, []);

  const groupedTasks = useMemo(() => {
    const storedTasks = tasks.map(task => task.title);
    if (storedTasks.length > 0) {
      return storedTasks;
    }
    return extractPlanTasksFromText(planSnapshot, 8);
  }, [planSnapshot, tasks]);

  const planLines = useMemo(() => {
    if (!planSnapshot) {
      return [];
    }

    return planSnapshot
      .split('\n')
      .map(line => line.trim())
      .filter(Boolean)
      .map(line => line.replace(/\*\*/g, ''))
      .map(line => line.replace(/^[-*•]\s*/, ''))
      .map(line => line.replace(/^\d+[.)]\s*/, ''))
      .map(line => line.trim())
      .filter(line => line.length > 0)
      .filter(line => !/^conversation history/i.test(line));
  }, [planSnapshot]);

  const timetableDays = useMemo(() => {
    const order = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    return [...timetable].sort((a, b) => {
      const dayDiff = order.indexOf(a.day) - order.indexOf(b.day);
      if (dayDiff !== 0) {
        return dayDiff;
      }
      return a.start.localeCompare(b.start);
    });
  }, [timetable]);

  return (
    <View style={styles.container}>
      <AnimatedGradientBackground palette={palette} />
      <ScrollView contentContainerStyle={[styles.content, {paddingTop: Math.max(18, insets.top + 8)}]}>
        <View style={styles.topRow}>
          <HamburgerButton palette={palette} onPress={() => setMenuVisible(true)} />
          <View>
            <Text style={[styles.overline, {color: palette.textSecondary}]}>Tasks</Text>
            <Text style={[styles.title, {color: palette.textPrimary}]}>My Tasks</Text>
            <Text style={[styles.subtitle, {color: palette.textMuted}]}>Plan tasks and recommendations generated by AI for daily preparation.</Text>
          </View>
        </View>

        <GlassCard palette={palette} style={styles.card}>
          <Text style={[styles.cardTitle, {color: palette.textPrimary}]}>What AI Prepared</Text>
          {planSnapshot ? (
            <View style={styles.planBlocks}>
              {planLines.length > 0 ? (
                planLines.map((line, index) => {
                  const isHeading = /^[A-Z][A-Z\s:-]{3,}$/.test(line) || /^section\b/i.test(line) || /^\d+\./.test(line);
                  const isBullet = /^([•*-]|\d+[.)])/.test(line) || /^(review|revise|practice|solve|read|prepare|schedule|focus|talk|identify|complete|break|work|study|revisit|go back|keep|avoid|build|improve|ask)\b/i.test(line);
                  return (
                    <Text
                      key={`${line}-${index}`}
                      style={[
                        isHeading ? styles.planHeading : isBullet ? styles.planBullet : styles.planParagraph,
                        {color: isHeading ? palette.textPrimary : palette.textSecondary},
                      ]}>
                      {isBullet ? `• ${line}` : line}
                    </Text>
                  );
                })
              ) : (
                <Text style={[styles.body, {color: palette.textSecondary}]}>{planSnapshot}</Text>
              )}
            </View>
          ) : (
            <Text style={[styles.body, {color: palette.textSecondary}]}>No saved plan yet. Ask AI for a study plan and it will appear here.</Text>
          )}
        </GlassCard>

        <GlassCard palette={palette} style={styles.card}>
          <Text style={[styles.cardTitle, {color: palette.textPrimary}]}>Daily Tasks</Text>
          {groupedTasks.length === 0 ? (
            <Text style={[styles.body, {color: palette.textSecondary}]}>No tasks generated yet.</Text>
          ) : (
            <View style={styles.taskList}>
              {groupedTasks.map((task, index) => (
                <View key={`${task}-${index}`} style={[styles.taskRow, {borderColor: palette.cardBorder, backgroundColor: palette.backgroundAlt}]}> 
                  <View style={[styles.indexBadge, {backgroundColor: palette.accentSoft}]}> 
                    <Text style={[styles.indexText, {color: palette.accent}]}>{index + 1}</Text>
                  </View>
                  <Text style={[styles.taskText, {color: palette.textPrimary}]}>{task}</Text>
                </View>
              ))}
            </View>
          )}
        </GlassCard>

        <GlassCard palette={palette} style={styles.card}>
          <Text style={[styles.cardTitle, {color: palette.textPrimary}]}>Study Timetable</Text>
          {timetableDays.length === 0 ? (
            <Text style={[styles.body, {color: palette.textSecondary}]}>No timetable saved yet. Ask AI for a timetable to enable reminders.</Text>
          ) : (
            <View style={styles.tableWrap}>
              {timetableDays.map(slot => (
                <View key={`${slot.day}-${slot.start}-${slot.task}`} style={[styles.slotRow, {borderColor: palette.cardBorder}]}> 
                  <View style={styles.slotMeta}>
                    <Text style={[styles.slotDay, {color: palette.textPrimary}]}>{slot.day}</Text>
                    <Text style={[styles.slotTime, {color: palette.textMuted}]}>{slot.start} - {slot.end}</Text>
                  </View>
                  <Text style={[styles.slotTask, {color: palette.textPrimary}]}>{slot.task}</Text>
                </View>
              ))}
            </View>
          )}
        </GlassCard>

        <GlassCard palette={palette} style={styles.card}>
          <Text style={[styles.cardTitle, {color: palette.textPrimary}]}>How To Use</Text>
          <Text style={[styles.body, {color: palette.textSecondary}]}>Open AI Coach, ask for a plan or timetable, and the app will store the tasks. The drawer item My Tasks will always show your latest preparation list and reminders.</Text>
        </GlassCard>
      </ScrollView>

      <SideDrawerMenu
        visible={menuVisible}
        onClose={() => setMenuVisible(false)}
        palette={palette}
        navigation={navigation}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 14,
  },
  overline: {
    fontSize: 11,
    fontFamily: Platform.select(typography.heading),
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  title: {
    marginTop: 6,
    fontSize: 30,
    lineHeight: 36,
    fontFamily: Platform.select(typography.display),
    fontWeight: '700',
  },
  subtitle: {
    marginTop: 4,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: Platform.select(typography.body),
  },
  card: {
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontFamily: Platform.select(typography.heading),
    fontWeight: '700',
    marginBottom: 8,
  },
  body: {
    fontSize: 14,
    lineHeight: 22,
    fontFamily: Platform.select(typography.body),
  },
  planBlocks: {
    gap: 10,
  },
  planHeading: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: Platform.select(typography.heading),
    fontWeight: '700',
  },
  planParagraph: {
    fontSize: 14,
    lineHeight: 23,
    fontFamily: Platform.select(typography.body),
    fontWeight: '500',
  },
  planBullet: {
    fontSize: 14,
    lineHeight: 23,
    fontFamily: Platform.select(typography.body),
    fontWeight: '600',
  },
  taskList: {
    gap: 8,
  },
  taskRow: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  indexBadge: {
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  indexText: {
    fontSize: 12,
    fontFamily: Platform.select(typography.heading),
    fontWeight: '700',
  },
  taskText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 21,
    fontFamily: Platform.select(typography.body),
    fontWeight: '600',
  },
  tableWrap: {
    gap: 8,
  },
  slotRow: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  slotMeta: {
    width: 96,
  },
  slotDay: {
    fontSize: 13,
    fontFamily: Platform.select(typography.heading),
    fontWeight: '700',
  },
  slotTime: {
    marginTop: 2,
    fontSize: 11,
    fontFamily: Platform.select(typography.body),
  },
  slotTask: {
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: Platform.select(typography.body),
    fontWeight: '600',
  },
});

export default MyTasksScreen;
